name: Build
on:
  push:
    branches:
      - master
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push 8.1
        uses: docker/build-push-action@v3
        with:
          file: "./src/docker/Dockerfile"
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            phpVersion=8.1
          tags: "${{ vars.BUILDKIT_IMAGE }}:8.1"
      -
        name: Build and push 8.1 alpine
        uses: docker/build-push-action@v3
        with:
          file: "./src/docker/Dockerfile.alpine"
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            phpVersion=8.1
          tags: "${{ vars.BUILDKIT_IMAGE }}:8.1-alpine"
      -
        name: Build and push 8.2
        uses: docker/build-push-action@v3
        with:
          file: "./src/docker/Dockerfile"
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            phpVersion=8.2
          tags: "${{vars.BUILDKIT_IMAGE}}:8.2"
      -
        name: Build and push 8.2 alpine
        uses: docker/build-push-action@v3
        with:
          file: "./src/docker/Dockerfile.alpine"
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            phpVersion=8.2
          tags: "${{vars.BUILDKIT_IMAGE}}:8.2-alpine"
      -
        name: Build and push 8.3
        uses: docker/build-push-action@v3
        with:
          file: "./src/docker/Dockerfile"
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            phpVersion=8.3
          tags: |
           "${{vars.BUILDKIT_IMAGE}}:8.3"
           "${{vars.BUILDKIT_IMAGE}}:latest"
      -
        name: Build and push 8.3 alpine
        uses: docker/build-push-action@v3
        with:
          file: "./src/docker/Dockerfile.alpine"
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            phpVersion=8.3
          tags: |
           "${{vars.BUILDKIT_IMAGE}}:8.3-alpine"
      -
        name: Build and push 8.4 RC
        uses: docker/build-push-action@v3
        with:
          file: "./src/docker/Dockerfile"
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            phpVersion=8.4.0RC4
          tags: |
           "${{vars.BUILDKIT_IMAGE}}:8.4.0RC4"
      -
        name: Build and push 8.4 RC alpine
        uses: docker/build-push-action@v3
        with:
          file: "./src/docker/Dockerfile.alpine"
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            phpVersion=8.4.0RC4
          tags: |
           "${{vars.BUILDKIT_IMAGE}}:8.4.0RC4-alpine"
