name: Manual-build
on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'Docker tag'
        required: true
        default: 'latest' 
        type: string
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push 7.2
        uses: docker/build-push-action@v3
        with:
          file: "./src/docker/7.2/Dockerfile"
          push: true
          tags: "${{vars.BUILDKIT_IMAGE}}:7.2"
      -
        name: Build and push 7.3
        uses: docker/build-push-action@v3
        with:
          file: "./src/docker/7.3/Dockerfile"
          push: true
          tags: "${{vars.BUILDKIT_IMAGE}}:7.3"
      -
        name: Build and push 7.4
        uses: docker/build-push-action@v3
        with:
          file: "./src/docker/7.4/Dockerfile"
          push: true
          tags: "${{vars.BUILDKIT_IMAGE}}:7.4"
      -
        name: Build and push 8.0
        uses: docker/build-push-action@v3
        with:
          file: "./src/docker/8.0/Dockerfile"
          push: true
          tags: "${{vars.BUILDKIT_IMAGE}}:8.0"
      -
        name: Build and push 8.1
        uses: docker/build-push-action@v3
        with:
          file: "./src/docker/Dockerfile"
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            phpVersion=8.1
          tags: "${{ vars.BUILDKIT_IMAGE }}:8.1"
      -
        name: Build and push 8.1 alpine
        uses: docker/build-push-action@v3
        with:
          file: "./src/docker/Dockerfile.alpine"
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            phpVersion=8.1
          tags: "${{ vars.BUILDKIT_IMAGE }}:8.1-alpine"
      -
        name: Build and push 8.2
        uses: docker/build-push-action@v3
        with:
          file: "./src/docker/Dockerfile"
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            phpVersion=8.2
          tags: "${{vars.BUILDKIT_IMAGE}}:8.2"
      -
        name: Build and push 8.2 alpine
        uses: docker/build-push-action@v3
        with:
          file: "./src/docker/Dockerfile.alpine"
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            phpVersion=8.2
          tags: "${{vars.BUILDKIT_IMAGE}}:8.2-alpine"
      -
        name: Build and push 8.3
        uses: docker/build-push-action@v3
        with:
          file: "./src/docker/Dockerfile"
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            phpVersion=8.3
          tags: |
           "${{vars.BUILDKIT_IMAGE}}:8.3"
      -
        name: Build and push 8.3 alpine
        uses: docker/build-push-action@v3
        with:
          file: "./src/docker/Dockerfile.alpine"
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            phpVersion=8.3
          tags: |
           "${{vars.BUILDKIT_IMAGE}}:8.3-alpine"
      -
       name: Build and push 8.4 alpine
       uses: docker/build-push-action@v3
       with:
         file: "./src/docker/Dockerfile.alpine"
         push: true
         platforms: linux/amd64,linux/arm64
         build-args: |
           phpVersion=8.4
         tags: |
          "${{vars.BUILDKIT_IMAGE}}:8.4-alpine"
      -
        name: Build and push 8.4
        uses: docker/build-push-action@v3
        with:
          file: "./src/docker/Dockerfile"
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            phpVersion=8.4
          tags: |
           "${{vars.BUILDKIT_IMAGE}}:8.4"
           "${{vars.BUILDKIT_IMAGE}}:latest"